import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="py-4 flex items-center w-full justify-between px-4">
          <h2 className="text-2xl">TopWorkeer</h2>
          <div className="flex items-center gap-4">
            <Link href="/about">ABOUT</Link>
            <Link href="/blog">BLOG</Link>
            <Link href="/count">COUNT</Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
